# Generated by Django 5.1.7 on 2025-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='main.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Hyundai', 'Hyundai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_body',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Q5', 'Q5'), ('Q6', 'Q6'), ('Q7', 'Q7'), ('Rs2', 'Rs2'), ('Rs3', 'Rs3'), ('Rs4', 'Rs4'), ('Rs5', 'Rs5'), ('Rs6', 'Rs6'), ('Rs7', 'Rs7'), ('RsQ8', 'RsQ8'), ('Serie 1', 'Serie 1'), ('Serie 3', 'Serie 3'), ('Serie 5', 'Serie 5'), ('X1', 'X1'), ('X5', 'X5'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('M6', 'M6'), ('M8', 'M8'), ('Fiesta', 'Fiesta'), ('Focus', 'Focus'), ('Mondeo', 'Mondeo'), ('Mustang', 'Mustang'), ('Kuga', 'Kuga'), ('Aventador', 'Aventador'), ('Diablo', 'Diablo'), ('Huracan', 'Huracan'), ('Revuelto', 'Revuelto'), ('Urus', 'Urus'), ('Urraco', 'Urraco'), ('C-Class', 'C-Class'), ('E-Class', 'E-Class'), ('GLA', 'GLA'), ('Yaris', 'Yaris'), ('Corolla', 'Corolla'), ('RAV4', 'RAV4'), ('Golf', 'Golf'), ('Passat', 'Passat'), ('Tiguan', 'Tiguan'), ('Polo', 'Polo'), ('Corsa', 'Corsa'), ('Astra', 'Astra'), ('Insignia', 'Insignia'), ('Mokka', 'Mokka'), ('Clio', 'Clio'), ('Megane', 'Megane'), ('Captur', 'Captur'), ('Kadjar', 'Kadjar'), ('208', '208'), ('308', '308'), ('3008', '3008'), ('2008', '2008'), ('i20', 'i20'), ('i30', 'i30'), ('Tucson', 'Tucson'), ('Santa Fe', 'Santa Fe')], max_length=50),
        ),
    ]
