# Generated by Django 5.1.7 on 2025-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_favorites_alter_car_brand_alter_car_car_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
