# Generated by Django 5.1.7 on 2025-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
