# Generated by Django 5.1.7 on 2025-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
