# Generated by Django 5.1.7 on 2025-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuală', 'Manuală'), ('Automată', 'Automată')], default='Manuală', max_length=20),
        ),
    ]
